runtime: php83
env: standard

handlers:
  - url: /favicon\.ico
    static_files: public/favicon.ico
    upload: public/favicon\.ico
  - url: /robots\.txt
    static_files: public/robots.txt
    upload: public/robots\.txt
  - url: /css
    static_dir: public/css
  - url: /js
    static_dir: public/js
  - url: /.*
    script: auto
