name: Deploy to AWS EC2

on:
  push:
    branches:
      - master  # Замените на вашу основную ветку

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_SONGS_AWS }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@your-ec2-public-ip << 'EOF'
            cd /var/www/pingcrm
            git pull origin main
            composer install --no-dev --optimize-autoloader
            php artisan migrate --seed
            sudo systemctl restart nginx
          EOF
